image: golang:latest

variables:
  GIT_SUBMODULE_STRATEGY: "recursive"

stages:
  - build

build:
  stage: build
  script:

    - make check

    - export GOOS=linux
    - export GOARCH=amd64
    - go build ./cmd/gglargs/
    - mv gglargs gglargs_${GOOS}_${GOARCH}

    - export GOOS=darwin
    - export GOARCH=amd64
    - go build ./cmd/gglargs/
    - mv gglargs gglargs_${GOOS}_${GOARCH}

    - export GOOS=linux
    - export GOARCH=arm64
    - go build ./cmd/gglargs/
    - mv gglargs gglargs_${GOOS}_${GOARCH}

    - export GOOS=darwin
    - export GOARCH=arm64
    - go build ./cmd/gglargs/
    - mv gglargs gglargs_${GOOS}_${GOARCH}
  artifacts:
    paths:
      - build/*.txt
      - build/*.bash
      - build/*.sh
      - gglargs_linux*
      - gglargs_darwin*
