image: golang:latest

stages:
  - build

build:
  stage: build
  script:

    - go test ./...

    - export GOOS=linux
    - export GOARCH=amd64
    - go build ./cmd/gglargs/
    - mv gglargs gglargs_${GOOS}_${GOARCH}

    - export GOOS=darwin
    - export GOARCH=amd64
    - go build ./cmd/gglargs/
    - mv gglargs gglargs_${GOOS}_${GOARCH}

    - export GOOS=linux
    - export GOARCH=arm64
    - go build ./cmd/gglargs/
    - mv gglargs gglargs_${GOOS}_${GOARCH}

    - export GOOS=darwin
    - export GOARCH=arm64
    - go build ./cmd/gglargs/
    - mv gglargs gglargs_${GOOS}_${GOARCH}
  artifacts:
    paths:
      - gglargs_linux*
      - gglargs_darwin*
